In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import mean_squared_error

In [2]:
bank=pd.read_csv("C:/Users/HP/Documents/bank.csv",sep=";")
bank.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [3]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [4]:
bank.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [5]:
label_encoder = preprocessing.LabelEncoder() 
bank['age']= label_encoder.fit_transform(bank['age'])
label_encoder.classes_

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 91, 92, 94, 95, 98], dtype=int64)

In [6]:
bank['job']= label_encoder.fit_transform(bank['job'])
label_encoder.classes_

array(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management',
       'retired', 'self-employed', 'services', 'student', 'technician',
       'unemployed', 'unknown'], dtype=object)

In [7]:
bank['marital']= label_encoder.fit_transform(bank['marital'])
label_encoder.classes_

array(['divorced', 'married', 'single', 'unknown'], dtype=object)

In [8]:
bank['education']= label_encoder.fit_transform(bank['education'])
label_encoder.classes_

array(['basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'illiterate',
       'professional.course', 'university.degree', 'unknown'],
      dtype=object)

In [9]:
bank['default']= label_encoder.fit_transform(bank['default'])
label_encoder.classes_

array(['no', 'unknown', 'yes'], dtype=object)

In [10]:
bank['housing']= label_encoder.fit_transform(bank['housing'])
label_encoder.classes_

array(['no', 'unknown', 'yes'], dtype=object)

In [11]:
bank['loan']= label_encoder.fit_transform(bank['loan'])
label_encoder.classes_

array(['no', 'unknown', 'yes'], dtype=object)

In [12]:
bank['contact']= label_encoder.fit_transform(bank['contact'])
label_encoder.classes_

array(['cellular', 'telephone'], dtype=object)

In [13]:
bank['month']= label_encoder.fit_transform(bank['month'])
label_encoder.classes_

array(['apr', 'aug', 'dec', 'jul', 'jun', 'mar', 'may', 'nov', 'oct',
       'sep'], dtype=object)

In [14]:
bank['day_of_week']= label_encoder.fit_transform(bank['day_of_week'])
label_encoder.classes_

array(['fri', 'mon', 'thu', 'tue', 'wed'], dtype=object)

In [15]:
bank['duration']= label_encoder.fit_transform(bank['duration'])
label_encoder.classes_

array([   0,    1,    2, ..., 3785, 4199, 4918], dtype=int64)

In [16]:
bank['campaign']= label_encoder.fit_transform(bank['campaign'])
label_encoder.classes_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39, 40, 41, 42, 43, 56], dtype=int64)

In [17]:
bank['pdays']= label_encoder.fit_transform(bank['pdays'])
label_encoder.classes_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  25,  26,  27,
       999], dtype=int64)

In [18]:
bank['previous']= label_encoder.fit_transform(bank['previous'])
label_encoder.classes_

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [19]:
bank['poutcome']= label_encoder.fit_transform(bank['poutcome'])
label_encoder.classes_

array(['failure', 'nonexistent', 'success'], dtype=object)

In [20]:
bank['emp.var.rate']= label_encoder.fit_transform(bank['emp.var.rate'])
label_encoder.classes_

array([-3.4, -3. , -2.9, -1.8, -1.7, -1.1, -0.2, -0.1,  1.1,  1.4])

In [21]:
bank['cons.price.idx']= label_encoder.fit_transform(bank['cons.price.idx'])
label_encoder.classes_

array([92.201, 92.379, 92.431, 92.469, 92.649, 92.713, 92.756, 92.843,
       92.893, 92.963, 93.075, 93.2  , 93.369, 93.444, 93.749, 93.798,
       93.876, 93.918, 93.994, 94.027, 94.055, 94.199, 94.215, 94.465,
       94.601, 94.767])

In [22]:
bank['cons.conf.idx']= label_encoder.fit_transform(bank['cons.conf.idx'])
label_encoder.classes_

array([-50.8, -50. , -49.5, -47.1, -46.2, -45.9, -42.7, -42. , -41.8,
       -40.8, -40.4, -40.3, -40. , -39.8, -38.3, -37.5, -36.4, -36.1,
       -34.8, -34.6, -33.6, -33. , -31.4, -30.1, -29.8, -26.9])

In [23]:
bank['euribor3m']= label_encoder.fit_transform(bank['euribor3m'])
label_encoder.classes_

array([0.634, 0.635, 0.636, 0.637, 0.638, 0.639, 0.64 , 0.642, 0.643,
       0.644, 0.645, 0.646, 0.649, 0.65 , 0.651, 0.652, 0.653, 0.654,
       0.655, 0.659, 0.663, 0.668, 0.672, 0.677, 0.682, 0.683, 0.684,
       0.685, 0.688, 0.69 , 0.692, 0.695, 0.697, 0.699, 0.7  , 0.701,
       0.702, 0.704, 0.706, 0.707, 0.708, 0.709, 0.71 , 0.711, 0.712,
       0.713, 0.714, 0.715, 0.716, 0.717, 0.718, 0.719, 0.72 , 0.721,
       0.722, 0.723, 0.724, 0.727, 0.728, 0.729, 0.73 , 0.731, 0.732,
       0.733, 0.735, 0.737, 0.739, 0.74 , 0.741, 0.742, 0.743, 0.744,
       0.748, 0.749, 0.75 , 0.752, 0.753, 0.754, 0.755, 0.761, 0.762,
       0.766, 0.767, 0.768, 0.77 , 0.771, 0.773, 0.778, 0.781, 0.782,
       0.788, 0.79 , 0.793, 0.797, 0.802, 0.803, 0.809, 0.81 , 0.813,
       0.819, 0.821, 0.822, 0.825, 0.827, 0.829, 0.834, 0.835, 0.838,
       0.84 , 0.843, 0.846, 0.849, 0.851, 0.854, 0.859, 0.861, 0.869,
       0.87 , 0.873, 0.876, 0.877, 0.878, 0.879, 0.88 , 0.881, 0.882,
       0.883, 0.884,

In [24]:
bank['nr.employed']= label_encoder.fit_transform(bank['nr.employed'])
label_encoder.classes_

array([4963.6, 4991.6, 5008.7, 5017.5, 5023.5, 5076.2, 5099.1, 5176.3,
       5191. , 5195.8, 5228.1])

In [25]:
dummy=pd.get_dummies(bank)
dummy.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y_no', 'y_yes'],
      dtype='object')

In [26]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().fit(dummy)
scaled_data=scaler.transform(dummy)
final= pd.DataFrame(scaled_data)

In [27]:
y=bank.y
x=bank[['age','job','marital','education','default','housing','loan','contact','month','day_of_week','duration','campaign','pdays','previous','poutcome','emp.var.rate','cons.conf.idx','euribor3m','nr.employed']]

In [28]:
from sklearn.feature_selection import SelectFromModel
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=100)

In [29]:
select=SelectFromModel(RandomForestClassifier(n_estimators = 100))
select.fit(train_x, train_y)
select.get_support()
selected_feat= train_x.columns[(select.get_support())]
len(selected_feat)
selected_feat

Index(['age', 'duration', 'euribor3m', 'nr.employed'], dtype='object')

In [30]:
from sklearn.linear_model import LogisticRegression as LR
model=LR(random_state=0).fit(train_x,train_y)
print("Train Score =",model.score(train_x,train_y))
print("Test Score =",model.score(test_x,test_y))
predicted_y=model.predict(test_x)

Train Score = 0.9091350531107739
Test Score = 0.9115076474872542


C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [32]:
regress=AdaBoostRegressor(random_state=0, n_estimators=100)
regress.fit(train_x, train_y)

ValueError: could not convert string to float: 'yes'

In [33]:
from sklearn.naive_bayes import GaussianNB
gnb= GaussianNB()
gnb.fit(train_x,train_y)

GaussianNB()